import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "UnivApply",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-dvh p-4">{children}</body>
    </html>
  );
}
